sudo: required

language: python

services:
  - docker

env:
  global:
    - PORTS="8069:8069"
    - LINKS="db:db"
    - DAEMONIZE="1"
    - ODOO_VERSION="10.0"

  matrix:
    - TESTS="1" ODOO_VERSION="10.0" DOCKER_CONTEXT="./tests/odoo10"
    - TESTS="1" ODOO_VERSION="9.0" DOCKER_CONTEXT="./tests/odoo9"
    - LINT_CHECK="1"

before_install:
  - docker build -t "tecnativa/odoo-base:${ODOO_VERSION}" --build-arg "ODOO_VERSION=${ODOO_VERSION}" ./
  - docker pull kiasaki/alpine-postgres
  - docker run -d -it -e POSTGRES_USER="odoo" -e POSTGRES_PASSWORD="odoopassword" --name="db" postgres:9.6-alpine

install:
  - git clone --depth=1 https://github.com/LasLabs/docker-quality-tools.git ${HOME}/docker-quality-tools
  - export PATH=${HOME}/docker-quality-tools/travis:${PATH}
  - travis_install_all

script:
  - travis_run_all

after_success:
  - travis_after_success_all
