sudo: required

language: python

python:
  - "3.6"

services:
  - docker

git:
  depth: 1

branches:
  only:
    - master

env:
  global:
    # Variables found by default in Docker Hub builder
    - DOCKER_REPO=tecnativa/doodba
  matrix:
    - DOCKER_TAG=7.0 PG_VERSIONS=9.6
    - DOCKER_TAG=8.0 PG_VERSIONS=10
    - DOCKER_TAG=9.0 PG_VERSIONS=11
    - DOCKER_TAG=10.0
    - DOCKER_TAG=11.0
    - DOCKER_TAG=12.0
    - DOCKER_TAG=13.0

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::=--force-confnew install docker-ce
  - pip install -r requirements-ci.txt

install:
  - chown -R $USER:$USER .
  - chmod -R +r .
  - ./hooks/build

script:
  - python -m unittest -v tests
